### ISSUE TITLE
question about upgrading services written to use the Xenon framework 

### ISSUE THREAD

**Issue by heckj** [vmware/xenon#7]
Question for y'all - was reading through https://github.com/vmware/xenon/wiki/Programming-Model, https://github.com/vmware/xenon/wiki/Side-by-Side-Upgrade, and https://github.com/vmware/xenon/wiki/Highly-Available-Task-Tutorial - was trying to understand how one might leverage Xenon to do an upgrade to a highly available distributed system.

It looks like the the mechanism would be to write code to handle the specific sequencing, with the idea that what you're upgrading from and two are two running, discrete instances of the service and you're primarily involved in migrating data between them with something like https://github.com/vmware/xenon/blob/master/xenon-common/src/main/java/com/vmware/xenon/services/common/MigrationTaskService.java, but it also seems to expose some of the deeper concepts into the request being make declaratively in JSON (the querySpec bit for partial data migration).

Is the idea that when doing an upgrade you'd basically be doing through a coordinated series of REST API requests to Xenon, creating instances of the new versions and then migrating? 

Is there an upgrade service concept in the code, or would something external need to also be aware of any HA constructs and migrating data with those as well?

**Comment by georgechrysanthakopoulos** [comment]
Hi , we usually do the following:
1) create some application aware xenon task service, lets call it UpgradeTaskService, that is given N factory links, on POST (when the task is created)
2) for each factory link, it kicks of a independent MigrationTask instance
3) if there are inter dependencies, instead of kicking of N parallel migration tasks, it "sequences" them so it migrates factories in the proper sequence
4) when all factories are migrated to the new, side by side cluster (or we are at 99% close) it can inform some front end edge device to temporarily queue client side requests, do one last migration pass, then let the edge device change its VIP/DNS to point to the new cluster

we have this working for vmware services using xenon, in pre production / beta. note there is no down time, just a little bit of "jitter" when we queue requests for a few seconds. Even that step is optional actually, since you can start direct client requests to the new cluster after a certain amount of data has moved over.

while all this is happening the production cluster is up and running, with no churn, which is why we recommend this "blue/green" approach.

**Comment by heckj** [comment]
Thanks George!

So it would primarily be in java code that Xenon loads by classpath or such, and the java code would include the relevant service factories and be responsible for any relevant sequencing? (just double checking). 

I don't support you have any dummy/sample code outlining how this is set up or providing an example to riff from?

**Comment by georgechrysanthakopoulos** [comment]
Factories are started, explicitly on service host start(), usually overriden by the "application" developer with their own start() method. See SampleHost.java, in xenon-samples, or ExampleServiceHost.java, etc

Now, for an example of how to kick of a migration task, the only available example is in TestMigrationTaskService, where we test the migration task using the example factory :) But it should be all you need, our internal examples just specify more factories etc.

For hints on how to write tasks, see the ExampleTaskTutorial. You can create your own task service, that starts the migration tasks in its STARTED phase, etc

**Comment by heckj** [comment]
Thanks @georgechrysanthakopoulos !
